export const DEFAULT_CLOCK_LABEL = '闹钟'
export const DEFAULT_CLOCK_FORMATTED_TIME = '00:00:00'
export const DEFAULT_CLOCK_INTERVAL = 0
export const DEFAULT_CLOCK_REPEAT = -1
export const DEFAULT_CLOCK_AUDIO_PATH = ''
