name: Build

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.2.0

      - name: Install Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build && npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD }}

      - name: upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ matrix.os }}
          path: dist

      - name: release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/**"
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD }}

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: |
          npx rimraf "dist/!(*.exe)"

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          npx rimraf "dist/!(*.dmg)"
